<?php

namespace ContainerMRtLSHV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DrXiURKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.drXiURK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.drXiURK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'bankrepository' => ['privates', 'App\\Repository\\BankRepository', 'getBankRepositoryService', true],
        ], [
            'bankrepository' => 'App\\Repository\\BankRepository',
        ]);
    }
}
