<?php

namespace ContainerMRtLSHV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T0HJzCVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.t0HJzCV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.t0HJzCV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'chemin_de_traverse' => ['privates', '.errored..service_locator.t0HJzCV.App\\Entity\\CheminDeTraverse', NULL, 'Cannot autowire service ".service_locator.t0HJzCV": it needs an instance of "App\\Entity\\CheminDeTraverse" but this type has been excluded in "config/services.yaml".'],
            'coin' => ['privates', '.errored..service_locator.t0HJzCV.App\\Entity\\Coin', NULL, 'Cannot autowire service ".service_locator.t0HJzCV": it needs an instance of "App\\Entity\\Coin" but this type has been excluded in "config/services.yaml".'],
        ], [
            'chemin_de_traverse' => 'App\\Entity\\CheminDeTraverse',
            'coin' => 'App\\Entity\\Coin',
        ]);
    }
}
