<?php

namespace ContainerMRtLSHV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OLqlaITService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oLqlaIT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oLqlaIT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'bank' => ['privates', '.errored..service_locator.oLqlaIT.App\\Entity\\Bank', NULL, 'Cannot autowire service ".service_locator.oLqlaIT": it needs an instance of "App\\Entity\\Bank" but this type has been excluded in "config/services.yaml".'],
        ], [
            'bank' => 'App\\Entity\\Bank',
        ]);
    }
}
