<?php

namespace ContainerMRtLSHV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6zjUsNuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6zjUsNu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6zjUsNu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cheminDeTraverse' => ['privates', '.errored..service_locator.6zjUsNu.App\\Entity\\CheminDeTraverse', NULL, 'Cannot autowire service ".service_locator.6zjUsNu": it needs an instance of "App\\Entity\\CheminDeTraverse" but this type has been excluded in "config/services.yaml".'],
        ], [
            'cheminDeTraverse' => 'App\\Entity\\CheminDeTraverse',
        ]);
    }
}
