<?php

namespace ContainerMRtLSHV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3IlqSnlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3IlqSnl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3IlqSnl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cheminDeTraverse' => ['privates', '.errored..service_locator.3IlqSnl.App\\Entity\\CheminDeTraverse', NULL, 'Cannot autowire service ".service_locator.3IlqSnl": it needs an instance of "App\\Entity\\CheminDeTraverse" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'cheminDeTraverse' => 'App\\Entity\\CheminDeTraverse',
            'entityManager' => '?',
        ]);
    }
}
