<?php

namespace ContainerMRtLSHV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCoin2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Py2Bz0F.App\Entity\Coin' shared service.
     *
     * @return \App\Entity\Coin
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Py2Bz0F": it needs an instance of "App\\Entity\\Coin" but this type has been excluded in "config/services.yaml".');
    }
}
