<?php

namespace ContainerMRtLSHV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheminDeTraverse4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.t0HJzCV.App\Entity\CheminDeTraverse' shared service.
     *
     * @return \App\Entity\CheminDeTraverse
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.t0HJzCV": it needs an instance of "App\\Entity\\CheminDeTraverse" but this type has been excluded in "config/services.yaml".');
    }
}
