<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMRtLSHV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMRtLSHV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMRtLSHV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMRtLSHV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMRtLSHV\App_KernelDevDebugContainer([
    'container.build_hash' => 'MRtLSHV',
    'container.build_id' => 'da7cd9cd',
    'container.build_time' => 1731412257,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMRtLSHV');
