<?php

namespace Container8rIY355;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Py2Bz0FService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Py2Bz0F' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Py2Bz0F'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'coin' => ['privates', '.errored..service_locator.Py2Bz0F.App\\Entity\\Coin', NULL, 'Cannot autowire service ".service_locator.Py2Bz0F": it needs an instance of "App\\Entity\\Coin" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'coin' => 'App\\Entity\\Coin',
            'entityManager' => '?',
        ]);
    }
}
