<?php

namespace Container8rIY355;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZtGLGaQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ztGLGaQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ztGLGaQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cheminDeTraverseRepository' => ['privates', 'App\\Repository\\CheminDeTraverseRepository', 'getCheminDeTraverseRepositoryService', true],
        ], [
            'cheminDeTraverseRepository' => 'App\\Repository\\CheminDeTraverseRepository',
        ]);
    }
}
