<?php

namespace Container8rIY355;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I71iz0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.I_71iz0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.I_71iz0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'coin' => ['privates', '.errored..service_locator.I_71iz0.App\\Entity\\Coin', NULL, 'Cannot autowire service ".service_locator.I_71iz0": it needs an instance of "App\\Entity\\Coin" but this type has been excluded in "config/services.yaml".'],
        ], [
            'coin' => 'App\\Entity\\Coin',
        ]);
    }
}
